### ISSUE TITLE
Add checklist for students to remember before submitting

### ISSUE THREAD

**Issue by meling** [uis-no/uis-thesis#25]
- [ ] Check that references are correctly formatted.
- [ ] Do not insert blank pages between chapters, table of contents and similar stuff. (If you intend to print your thesis, then this can be useful, but nowadays most people read the thesis on screen, and it is annoying to scroll over empty pages.)
- [ ] Use the `~` symbol to keep references together with a specific word, e.g., `Paxos~\cite{paxos}`.
- [ ] Use the `cleveref` package and the `\cref` command to properly cross-reference chapters, sections, figures, algorithms, listings, theorems, definitions etc.
- [ ] Make sure that your page numbers are aligned with the PDF's page numbers.
- [ ] Try to avoid overfull or underfull paragraphs/pages.
- [ ] Borrow from other checklists
